# Sets the python version
FROM python:3.9.1-slim

LABEL maintainer="Alexandre Xavier <ale.bxsantos@gmail.com>"

# Allows the logs generated by python apps to be rendered in the terminal
ENV PYTHONUNBUFFERED 1

# Sets the default shell to bash
ENV SHELL /bin/bash

# Creates a non-root user
RUN adduser --disabled-password docker

RUN apt-get update \
    && apt-get install -y git

# Upgrades pip
RUN pip install --upgrade pip

# Poetry project setup for development
# Copies poetry requirements files
COPY --chown=docker dev.Dockerfile poetry.lock* pyproject.toml* ./

RUN pip install poetry \
    && poetry config virtualenvs.create false --local \
    && poetry install

# Pipenv project setup for production
# install pipenv, dependencies and cleans up
# RUN pip install pipenv \
#     && pipenv install --system --deploy --ignore-pipfile \

# Clean up
RUN apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

# Applies the container user to be non-root
USER docker

WORKDIR /home/docker

# Sets the binaries to path
ENV PATH="/home/docker/.local/bin:${PATH}"

# Copy in as non-root user, so permissions match what we need
COPY --chown=docker:docker . .