# Generated by Django 3.1.7 on 2021-04-03 21:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('address', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=40)),
                ('province', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('country', models.CharField(max_length=40)),
                ('postal_code', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('fax', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('email', models.CharField(max_length=60)),
                ('support_rep', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee')),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice_date', models.DateTimeField()),
                ('billing_address', models.CharField(max_length=70)),
                ('billing_city', models.CharField(max_length=40)),
                ('billing_state', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('billing_country', models.CharField(max_length=40)),
                ('billing_postal_code', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('play_list', models.CharField(max_length=60)),
                ('customer', models.ManyToManyField(to='customer.Customer')),
                ('track', models.ManyToManyField(to='music.Track')),
            ],
            options={
                'ordering': ('play_list',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.invoice')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.track')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
